name: Run Qt Regression tests

on: [push]


jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Install libmesa
      run:  sudo apt install libglu1-mesa-dev freeglut3-dev
    - name: Install Qt
      uses: jurplel/install-qt-action@v1
    - uses: actions/checkout@v1
    - name: list
      run: ls -a
    - name: qmake
      run: qmake BUILD-ALL.pro CONFIG+=debug
    - name: make qmake_all
      run: make qmake_all
    - name: make
      run: make -j2 && ls -a
    - name: Upload MacroAssembler Unit Tests
      uses: actions/upload-artifact@v1
      with:
          name: MacroAssembler
          path: MacroAssembler/MacroAssembler
      
  run_asm_test:
    runs-on: ubuntu-18.04
    needs: [build-linux]
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v1
      with:
          name: MacroAssembler
    - name: Install Qt
      uses: jurplel/install-qt-action@v1
    - name: Run MacroAssembler Tests
      run:  cd MacroAssembler && sudo chmod +x MacroAssembler && ./MacroAssembler -silent > MacroAsmUnits.txt
    - name: Upload error logs
      if: failure()
      uses: actions/upload-artifact@master
      with:
          name: MacroTestErrLog
          path: MacroAssembler/MacroAsmUnits.txt
