name: Run Qt Regression tests

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libmesa
      run:  sudo apt install libglu1-mesa-dev freeglut3-dev
    - name: Install Qt
      uses: jurplel/install-qt-action@v1
    - uses: actions/checkout@v1
    - name: list
      run: ls -a
    - name: qmake
      run: qmake pep10unit/pep10unit.pro CONFIG+=debug
    - name: make qmake_all
      run: make qmake_all
    - name: make
      run: make -j2
      
  run_asm_test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Echo top level contents
      run: ls -a
    - name: Echo MA contents
      run: ls -a MacroAssembler
    - name: Run MacroAssembler Tests
      run:  cd MacroAssembler && ./MacroAssembler
