name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install libmesa
      run:  sudo apt install libglu1-mesa-dev freeglut3-dev
    - name: Install Qt
      uses: jurplel/install-qt-action@v1
    - uses: actions/checkout@v1
    - name: list
      run: ls -a
    - name: qmake
      run: qmake pep10unit/pep10unit.pro CONFIG+=debug
    - name: make qmake_all
      run: make qmake_all
    - name: make
      run: make
    - name: run unit
      run: ls -a && ls -a "MacroAssembler"
